var baseURL = '../../';
var cashDate = 'date=20200506_0752';
document.write('<link rel="stylesheet" href="'+baseURL+'css/libs/animate.css?'+cashDate+'" />');
document.write('<link rel="stylesheet" href="'+baseURL+'css/libs/plugins.css?'+cashDate+'" />');
document.write('<link rel="stylesheet" href="'+baseURL+'css/ui/base.css?'+cashDate+'" />');
document.write('<link rel="stylesheet" href="'+baseURL+'css/ui/layout.css?'+cashDate+'" />');
//document.write('<link rel="stylesheet" href="'+baseURL+'css/ui/components.css?'+cashDate+'" />');
document.write('<link rel="stylesheet" href="'+baseURL+'css/ui/utilities.css?'+cashDate+'" />');
//document.write('<link rel="stylesheet" href="'+baseURL+'css/ui/content.css?'+cashDate+'" />');
document.write('<link rel="stylesheet" href="'+baseURL+'css/ui/ui.css?'+cashDate+'" />');
document.write('<link rel="stylesheet" href="'+baseURL+'css/ui/setting.css?'+cashDate+'" />');
document.write('<link rel="stylesheet" href="'+baseURL+'css/ui/theme.css?'+cashDate+'" />');
document.write('<script src="'+baseURL+'js/libs/jquery.min.js?'+cashDate+'"></script>');
document.write('<script src="'+baseURL+'js/libs/librarys.min.js?'+cashDate+'"></script>');
document.write('<script src="'+baseURL+'js/ui/ui.common.js?'+cashDate+'"></script>');
document.write('<!--[if lt IE 9]>');
document.write('<script src="'+baseURL+'js/libs/html5shiv-printshiv.js?'+cashDate+'"></script>');
document.write('<![endif]-->');